### ISSUE TITLE
JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by kasrahabib** [shinalone/translate_api#1]
Hi, 

I am trying to translate some reviews from English to Persian. Last time I used this API, it translated about 4K reviews and after that, I get the error below: 

JSONDecodeError                           Traceback (most recent call last)
<ipython-input-8-0c6f7c73b843> in <module>()
----> 1 translate_api.api('a new text', 'en', 'fa')

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/translate_api/translate_api.py in api(text, from_language, to_language, host, proxy)

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/translate_api/translate_api.py in translate(self, eng_txt, TK, from_language, to_language, host, proxy)

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/requests/models.py in json(self, **kwargs)
    894                     # used.
    895                     pass
--> 896         return complexjson.loads(self.text, **kwargs)
    897 
    898     @property

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py in loads(s, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    346             parse_int is None and parse_float is None and
    347             parse_constant is None and object_pairs_hook is None and not kw):
--> 348         return _default_decoder.decode(s)
    349     if cls is None:
    350         cls = JSONDecoder

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py in decode(self, s, _w)
    335 
    336         """
--> 337         obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    338         end = _w(s, end).end()
    339         if end != len(s):

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py in raw_decode(self, s, idx)
    353             obj, end = self.scan_once(s, idx)
    354         except StopIteration as err:
--> 355             raise JSONDecodeError("Expecting value", s, err.value) from None
    356         return obj, end

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by shinalone** [comment]
@kasrahabib I'm sorry I didn't notice your email until now. you check to see if the module is being used correctly. For instance: 
![https://i.imgur.com/iN7Yzf0.png](https://i.imgur.com/iN7Yzf0.png)

**Comment by kasrahabib** [comment]
@shinalone , it I am running the same code but it's not working in my case.
